AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Save form to S3 
Parameters:
  AppStage:
    Type: String
    Default: api
    Description: API Gateway stage, used as a prefix for the endpoint URLs
    AllowedPattern: ^[A-Za-z]+$
    MaxLength: 10
    MinLength: 1
    ConstraintDescription: "1-10 Latin letters"
Resources:
  UploadS3Bucket:
    Type: AWS::S3::Bucket
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref AppStage
  ShowFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user-form/
      Handler: show-form.lambdaHandler
      Runtime: nodejs12.x
      Events:
        ShowForm:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref WebApi
  ProcessFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user-form/
      Handler: process-form.lambdaHandler
      Runtime: nodejs12.x
      Events:
        SubmitForm:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref WebApi
      Environment: 
        Variables:
          UPLOAD_S3_BUCKET: !Ref UploadS3Bucket
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref UploadS3Bucket
Outputs:
  UserFormApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/"
  UploadBucket:
    Description: "S3 Bucket for user information"
    Value: !Ref UploadS3Bucket